#!/usr/bin/with-contenv bash

exec 2>&1

echo "[mysql] Starting service..."

mkdir -p /var/run/mysqld/ 2>/dev/null
mkdir -p /var/log/mysql/  2>/dev/null
mkdir -p /var/lib/mysql/  2>/dev/null
mkdir -p ${DATADIR:-/var/lib/mysql}   2>/dev/null
chown -R mysql:mysql /var/log/mysql/  2>/dev/null
chown -R mysql:mysql /var/lib/mysql/  2>/dev/null
chown -R mysql:mysql /var/run/mysqld/ 2>/dev/null

. ./dbinit.sh &

exec /usr/local/bin/gosu mysql:mysql /usr/sbin/mysqld --user=mysql --datadir="${DATADIR:-/var/lib/mysql}"
